version: "3"
services:
  backend:
    build: ./backend
    container_name: nest_backend
    depends_on:
      - db
    env_file:
      - ./backend/.env.production
    ports:
      - "3000:3000"
    command: npm run start
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build: ./frontend
    container_name: nginx_frontend
    depends_on:
      - backend
    ports:
      - "4000:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf

  db:
    container_name: db_postgres
    image:  postgres:16
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env.production